name: the_utils
description: A dart utils library.
version: 2.0.1
repository: https://github.com/jacklee1995/dart_utils
homepage: https://github.com/jacklee1995/dart_utils

environment:
  sdk: ^3.2.3

dependencies:
  intl: ^0.19.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
